# Generated by Django 4.2.4 on 2023-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='to_forum',
        ),
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
