# Generated by Django 4.2.4 on 2023-08-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_forum_comment_to_forum_forum_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
