# Generated by Django 4.2.4 on 2023-08-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='forum.comment'),
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
    ]
