# Generated by Django 4.2.4 on 2023-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
